//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceManager.Language {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locales() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaceManager.Language.Locales", typeof(Locales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new boat type.
        /// </summary>
        public static string AddNewBoatType {
            get {
                return ResourceManager.GetString("AddNewBoatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Air wraft.
        /// </summary>
        public static string AirDraft {
            get {
                return ResourceManager.GetString("AirDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authors :.
        /// </summary>
        public static string AuthorsGroupe {
            get {
                return ResourceManager.GetString("AuthorsGroupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You&apos;re currently logged with .
        /// </summary>
        public static string Currently {
            get {
                return ResourceManager.GetString("Currently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Development.
        /// </summary>
        public static string Dev {
            get {
                return ResourceManager.GetString("Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à environment will display more detailed information about the error that occurred..
        /// </summary>
        public static string DevDesc {
            get {
                return ResourceManager.GetString("DevDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Development Mode.
        /// </summary>
        public static string DevMod {
            get {
                return ResourceManager.GetString("DevMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Development environment shouldn&apos;t be enabled for deployed applications..
        /// </summary>
        public static string DevModDesc1 {
            get {
                return ResourceManager.GetString("DevModDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It can result in displaying sensitive information from exceptions to end users..
        /// </summary>
        public static string DevModDesc2 {
            get {
                return ResourceManager.GetString("DevModDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à For local debugging, enable the.
        /// </summary>
        public static string DevModDesc3 {
            get {
                return ResourceManager.GetString("DevModDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à environment by setting the.
        /// </summary>
        public static string DevModDesc4 {
            get {
                return ResourceManager.GetString("DevModDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à environment variable to.
        /// </summary>
        public static string DevModDesc5 {
            get {
                return ResourceManager.GetString("DevModDesc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à and restarting the app..
        /// </summary>
        public static string DevModDesc6 {
            get {
                return ResourceManager.GetString("DevModDesc6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not found.
        /// </summary>
        public static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while processing your request..
        /// </summary>
        public static string ErrorDesc {
            get {
                return ResourceManager.GetString("ErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://github.com/Le-clan-des-Semi-Croustillant/SRSP-Race-Manager.
        /// </summary>
        public static string Github {
            get {
                return ResourceManager.GetString("Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This page will allow you to import your gpx files and to modify them if necessary..
        /// </summary>
        public static string GpxDesc {
            get {
                return ResourceManager.GetString("GpxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .gpx file.
        /// </summary>
        public static string GpxFile {
            get {
                return ResourceManager.GetString("GpxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gpx File.
        /// </summary>
        public static string GpxFile2 {
            get {
                return ResourceManager.GetString("GpxFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import gpx file.
        /// </summary>
        public static string GpxFileIm {
            get {
                return ResourceManager.GetString("GpxFileIm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This page will allow you to import your .grid files and to modify them..
        /// </summary>
        public static string GridDesc {
            get {
                return ResourceManager.GetString("GridDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .grid file.
        /// </summary>
        public static string GridFile {
            get {
                return ResourceManager.GetString("GridFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grid File.
        /// </summary>
        public static string GridFile2 {
            get {
                return ResourceManager.GetString("GridFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Grid file.
        /// </summary>
        public static string GridFileIm {
            get {
                return ResourceManager.GetString("GridFileIm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See documentations and tutorials.
        /// </summary>
        public static string HelpDesc {
            get {
                return ResourceManager.GetString("HelpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hull length.
        /// </summary>
        public static string HullLength {
            get {
                return ResourceManager.GetString("HullLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hull width.
        /// </summary>
        public static string HullWidth {
            get {
                return ResourceManager.GetString("HullWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Request ID:.
        /// </summary>
        public static string IdReq {
            get {
                return ResourceManager.GetString("IdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server support for IPv4 addresses: .
        /// </summary>
        public static string IPV4support {
            get {
                return ResourceManager.GetString("IPV4support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server support for IPv6 addresses: .
        /// </summary>
        public static string IPV6support {
            get {
                return ResourceManager.GetString("IPV6support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage boat types.
        /// </summary>
        public static string ManageBoatTypes {
            get {
                return ResourceManager.GetString("ManageBoatTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New.
        /// </summary>
        public static string NewBoatType {
            get {
                return ResourceManager.GetString("NewBoatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New-polar.
        /// </summary>
        public static string NewPolar {
            get {
                return ResourceManager.GetString("NewPolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You&apos;re not authorized to reach this page. You need to log in..
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorry, there&apos;s nothing at this address..
        /// </summary>
        public static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Overall length.
        /// </summary>
        public static string OverallLength {
            get {
                return ResourceManager.GetString("OverallLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Overall width.
        /// </summary>
        public static string OverallWidth {
            get {
                return ResourceManager.GetString("OverallWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://le-clan-des-semi-croustillant.github.io/SRSP-Race-Manager/.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parameter.
        /// </summary>
        public static string Param {
            get {
                return ResourceManager.GetString("Param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This section details the various parameters of the Race Manager interface..
        /// </summary>
        public static string ParamDesc {
            get {
                return ResourceManager.GetString("ParamDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorry.
        /// </summary>
        public static string Pardon {
            get {
                return ResourceManager.GetString("Pardon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port {0} is unavailable.
        /// </summary>
        public static string PortUnavailable {
            get {
                return ResourceManager.GetString("PortUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can find this project and its documentation through the.
        /// </summary>
        public static string ProjectDocumentation {
            get {
                return ResourceManager.GetString("ProjectDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This project is part of the Sailing Race Simulation Platform and is actively developed under.
        /// </summary>
        public static string RMDevelopedUnder {
            get {
                return ResourceManager.GetString("RMDevelopedUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See more.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See this project on Github.
        /// </summary>
        public static string SeethisprojectonGithub {
            get {
                return ResourceManager.GetString("SeethisprojectonGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server configuration.
        /// </summary>
        public static string ServConf {
            get {
                return ResourceManager.GetString("ServConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server is not running.
        /// </summary>
        public static string ServerNotRunning {
            get {
                return ResourceManager.GetString("ServerNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server is running.
        /// </summary>
        public static string ServerRunning {
            get {
                return ResourceManager.GetString("ServerRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web application and server settings..
        /// </summary>
        public static string SettingsDesc {
            get {
                return ResourceManager.GetString("SettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Swapping to.
        /// </summary>
        public static string SwapTo {
            get {
                return ResourceManager.GetString("SwapTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you have any trouble please check the.
        /// </summary>
        public static string Trouble {
            get {
                return ResourceManager.GetString("Trouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Turn off the server.
        /// </summary>
        public static string TurnOffTheServer {
            get {
                return ResourceManager.GetString("TurnOffTheServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Turn on the server.
        /// </summary>
        public static string TurnOnTheServer {
            get {
                return ResourceManager.GetString("TurnOnTheServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View docs.
        /// </summary>
        public static string Viewdocs {
            get {
                return ResourceManager.GetString("Viewdocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Determining session state, please wait....
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to the SRSP-Race-Manager..
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
