//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceManager.locales {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locale() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaceManager.locales.locale", typeof(locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration.
        /// </summary>
        public static string Conf {
            get {
                return ResourceManager.GetString("Conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This part details the server configuration, i.e. the IP address and the ports used..
        /// </summary>
        public static string ConfDesc {
            get {
                return ResourceManager.GetString("ConfDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Development.
        /// </summary>
        public static string Dev {
            get {
                return ResourceManager.GetString("Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à environment will display more detailed information about the error that occurred..
        /// </summary>
        public static string DevDesc {
            get {
                return ResourceManager.GetString("DevDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Development Mode.
        /// </summary>
        public static string DevMod {
            get {
                return ResourceManager.GetString("DevMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Development environment shouldn&apos;t be enabled for deployed applications..
        /// </summary>
        public static string DevModDesc1 {
            get {
                return ResourceManager.GetString("DevModDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It can result in displaying sensitive information from exceptions to end users..
        /// </summary>
        public static string DevModDesc2 {
            get {
                return ResourceManager.GetString("DevModDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à For local debugging, enable the.
        /// </summary>
        public static string DevModDesc3 {
            get {
                return ResourceManager.GetString("DevModDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à environment by setting the.
        /// </summary>
        public static string DevModDesc4 {
            get {
                return ResourceManager.GetString("DevModDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à environment variable to.
        /// </summary>
        public static string DevModDesc5 {
            get {
                return ResourceManager.GetString("DevModDesc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à and restarting the app..
        /// </summary>
        public static string DevModDesc6 {
            get {
                return ResourceManager.GetString("DevModDesc6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while processing your request..
        /// </summary>
        public static string ErrorDesc {
            get {
                return ResourceManager.GetString("ErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This page will allow you to import your gpx files and to modify them if necessary..
        /// </summary>
        public static string GpxDesc {
            get {
                return ResourceManager.GetString("GpxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .gpx file.
        /// </summary>
        public static string GpxFile {
            get {
                return ResourceManager.GetString("GpxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gpx File.
        /// </summary>
        public static string GpxFile2 {
            get {
                return ResourceManager.GetString("GpxFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import gpx file.
        /// </summary>
        public static string GpxFileIm {
            get {
                return ResourceManager.GetString("GpxFileIm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This page will allow you to import your grid files and modify them if necessary..
        /// </summary>
        public static string GridDesc {
            get {
                return ResourceManager.GetString("GridDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .grid file.
        /// </summary>
        public static string GridFile {
            get {
                return ResourceManager.GetString("GridFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grid File.
        /// </summary>
        public static string GridFile2 {
            get {
                return ResourceManager.GetString("GridFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Grid file.
        /// </summary>
        public static string GridFileIm {
            get {
                return ResourceManager.GetString("GridFileIm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Request ID:.
        /// </summary>
        public static string IdReq {
            get {
                return ResourceManager.GetString("IdReq", resourceCulture);
        ///   Recherche une chaîne localisée semblable à See documentations and tutorials.
        /// </summary>
        public static string HelpDesc {
            get {
                return ResourceManager.GetString("HelpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server support for IPv4 addresses: .
        /// </summary>
        public static string IPV4support {
            get {
                return ResourceManager.GetString("IPV4support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server support for IPv6 addresses: .
        /// </summary>
        public static string IPV6support {
            get {
                return ResourceManager.GetString("IPV6support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parameter.
        /// </summary>
        public static string Param {
            get {
                return ResourceManager.GetString("Param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This section details the various parameters of the Race Manager interface..
        /// </summary>
        public static string ParamDesc {
            get {
                return ResourceManager.GetString("ParamDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port {0} is unavailable.
        /// </summary>
        public static string PortUnavailable {
            get {
                return ResourceManager.GetString("PortUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Race Manager.
        /// </summary>
        public static string RaceManager {
            get {
                return ResourceManager.GetString("RaceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See more.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server Configuration.
        /// </summary>
        public static string ServConf {
            get {
                return ResourceManager.GetString("ServConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Swapping to.
        /// </summary>
        public static string SwapTo {
            get {
                return ResourceManager.GetString("SwapTo", resourceCulture);
        ///   Recherche une chaîne localisée semblable à Configure the server and web application settings..
        /// </summary>
        public static string SettingsDesc {
            get {
                return ResourceManager.GetString("SettingsDesc", resourceCulture);
            }
        }
    }
}
